# Change these first
owner: raspbian-addons # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main Site
    url: https://raspbian-addons.org
  - name: APT Repository
    url: https://apt.raspbian-addons.org
  - name: Docs
    url: https://docs.raspbian-addons.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.raspbian-addons.org
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.jsdelivr.net/gh/raspbian-addons/raspbian-addons@master/icons/logo-condensed-test.png
  name: Raspbian Addons
  introTitle: "**Raspbian Addons** is a legendary APT repository for Raspberry Pies containing Free and Open Source Software."
  introMessage: Welcome to the Raspbian Addons status site. Check on the uptime of our servers here. 
